INSERT INTO user VALUES(1001,CURRENT_TIMESTAMP, 'AB');
INSERT INTO user VALUES(1002,CURRENT_TIMESTAMP, 'CD');
INSERT INTO user VALUES(1003,CURRENT_TIMESTAMP, 'EF');
INSERT INTO post VALUES(1101,'My FIrst Post : AB', 1001);
INSERT INTO post VALUES(1102,'My SEcond Post : AB', 1001);